name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          set -x
          yarn install --frozen-lock
      - name: Test
        run: |
          set -x
          yarn test
